project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Danielle Janney's Portfolio"
    
  page-footer:
    left: "&copy; Copyright 2023, Danielle Janney"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/daniellejanney/
      - icon: github
        href: https://github.com/djanney1/LISPortfolio
    
  navbar:
    background: "#9CD5FF"
    search: true
    right:
      - text: "Leadership and Innovation"
        href: leadership-and-innovation.qmd
      - text: "Systems and Services"
        href: systems-and-services.qmd
      - text: "Knowledge Representation"
        href: knowledge-representation.qmd
      - text: "Theory and Praxis"
        href: theory-and-praxis.qmd
      - text: "More"
        menu: 
          - text: "CV"
            href: img/cv.pdf
          - text: "Certificates"
            href: certificates.qmd
          - text: "Art"
            href: art.qmd
        
format:
  html:
    theme: cosmo
    toc: true

editor: source