project:
  type: website
  output-dir: docs
  
website:
  title: "Danielle Janney's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - art.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/daniellejanney/
      - icon: github
        href: https://github.com/djanney1/LISPortfolio
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Danielle Janney"

format:
  html:
    theme: cerulean
    toc: true

editor: source

